### ISSUE TITLE
Unable to deploy (through "make helm-deploy") in OpenShift

### ISSUE THREAD

**Issue by sarroutbi** [keylime/attestation-operator#33]
I tried to perform `make helm-deploy` in OpenShift and I am getting pods that go to `Error` state:

```bash
$ oc get pods -nkeylime
NAME                         READY   STATUS   RESTARTS   AGE
hhkl-keylime-init-ca-jgnsp   0/1     Error    0          36m
hhkl-keylime-init-ca-z5zs2   0/1     Error    0          36m

$ oc logs -f hhkl-keylime-init-ca-jgnsp -n keylime
/usr/bin/kubectl
Error from server (NotFound): secrets "hhkl-keylime-certs" not found
INFO:keylime.config:option "password" for component ca.conf was overriden by environment variable KEYLIME_CA_PASSWORD
Traceback (most recent call last):
  File "/usr/local/bin/keylime_ca", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keylime/cmd/ca.py", line 7, in main
    ca_util.main()
  File "/usr/local/lib/python3.11/site-packages/keylime/ca_util.py", line 417, in main
    cmd_init(workingdir)
  File "/usr/local/lib/python3.11/site-packages/keylime/ca_util.py", line 166, in cmd_init
    cacert, ca_pk, _ = ca_impl.mk_cacert()  # pylint: disable=W0632
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keylime/ca_impl_openssl.py", line 80, in mk_cacert
    cert_req, privkey = mk_request(config.getint("ca", "cert_bits"), name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keylime/ca_impl_openssl.py", line 59, in mk_request
    privkey = rsa.generate_private_key(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 131, in generate_private_key
    _verify_rsa_parameters(public_exponent, key_size)
  File "/usr/lib64/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 143, in _verify_rsa_parameters
    raise ValueError("key_size must be at least 512-bits.")
ValueError: key_size must be at least 512-bits.
ERROR: unable to generete certificates
```

This seems to be related to a problem with SCC or similar, as I get it working with `minikube`

**Comment by sarroutbi** [comment]
This seems to be related to the Service Accounts in OpenShift.

- Service Accounts in OpenShift need to be granted with 'anyuid' permissions:
```bash
oc login -u system:admin -n keylime
oc adm policy add-scc-to-user anyuid -z hhkl-keylime-init
```

- After that, I get crashing pods:
```bash
$ oc get pods
NAME                                      READY   STATUS             RESTARTS      AGE
hhkl-keylime-registrar-69b468dc74-6dlcn   0/1     CrashLoopBackOff   5 (77s ago)   4m23s
hhkl-keylime-tenant-6dd75f69fd-7hchf      1/1     Running            0             4m23s
hhkl-keylime-verifier-0                   0/1     CrashLoopBackOff   5 (77s ago)   4m23s
```

- As each of the elements (registrar, verifier) have its own service account, to fix them, can configure each of the service accounts, then delete them (for them to reboot):
```
$ oc get sa
NAME                     SECRETS   AGE
builder                  1         63m
default                  1         63m
deployer                 1         63m
hhkl-keylime-agent       1         5m19s
hhkl-keylime-init        1         5m31s
hhkl-keylime-registrar   1         5m19s
hhkl-keylime-tenant      1         5m19s
hhkl-keylime-verifier    1         5m19s
$ oc adm policy add-scc-to-user anyuid -z hhkl-keylime-verifier
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:anyuid added: "hhkl-keylime-verifier"
$ oc adm policy add-scc-to-user anyuid -z hhkl-keylime-registrar
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:anyuid added: "hhkl-keylime-registrar"
$ oc delete pod hhkl-keylime-registrar-69b468dc74-6dlcn
$ oc delete pod hhkl-keylime-verifier-0
```

- After that, everything gets to run appropriately:
```bash
$ oc get pod
NAME                                      READY   STATUS    RESTARTS   AGE
hhkl-keylime-registrar-69b468dc74-9kq68   1/1     Running   0          6m29s
hhkl-keylime-tenant-6dd75f69fd-hrv86      1/1     Running   0          9m10s
hhkl-keylime-verifier-0                   1/1     Running   0          6m28s
```
I will investigate a "polite" way of configuring each of the service accounts so that they run appropriately in both Vanilla K8S and OpenShift

**Comment by mheese** [comment]
@sarroutbi as previously discussed there are probably several adjustments that we will have to make in OpenShift so that the security context constraints are satisfied. There are several ways to go about this - both in terms of how to deal with the SCCs in OpenShift (for example, we could create/manage specific ones and request these for the resources/service accounts that we create), as well as on how to deploy in OpenShift in general.

For example, previously I always simply had an "openshift=true" value in helm because it was easy and wasn't too difficult to use either. However, it would actually be great if that is not necessary at all. Maybe by now there are some common detection mechanisms for that?
